# UI Colors (extended)
accent = "#6E6A64"
cursor = "#544f51"

# Primary colors
foreground = "#CFCDC9"
background = "#0B0C0C"

# Selection colors
selection_foreground = "#0B0C0C"
selection_background = "#CFCDC9"

# Normal colors (ANSI 0-7)
color0 = "#0B0C0C"
color1 = "#f24331"
color2 = "#6E6A64"
color3 = "#5C5852"
color4 = "#92958a"
color5 = "#aaa8a4"
color6 = "#a97b7d"
color7 = "#CAC8C4"

# Bright colors (ANSI 8-15)
color8 = "#666666"
color9 = "#f24331"
color10 = "#6E6A64"
color11 = "#5C5852"
color12 = "#92958a"
color13 = "#aaa8a4"
color14 = "#a97b7d"
color15 = "#434549"
