-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/turbonite/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(48191bee)", "rgba(666a6dee)", "rgba(37393Aee)", "rgba(0B0C0Cee)", "rgba(48191bee)" },
        angle = 45,
      },
      inactive_border = "rgb(131415)",
    },
    gaps_in = 7,
    gaps_out = 11,
    border_size = 2,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 6,
    rounding_power = 3,
    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(00000088)",
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
