
# ========= Border =========
file_panel_border = '#b9b9b9'
sidebar_border = '#b9b9b9'
footer_border = '#b9b9b9'

# ========= Border Active =========
file_panel_border_active = '#92958a'
sidebar_border_active = '#92958a'
footer_border_active = '#92958a'
modal_border_active = '#92958a'

# ========= Background (bg) =========
full_screen_bg = '#0d0d0c'
file_panel_bg = '#0d0d0c'
sidebar_bg = '#0d0d0c'
footer_bg = '#0d0d0c'
modal_bg = '#0d0d0c'

# ========= Foreground (fg) =========
full_screen_fg = '#b9b9b9'
file_panel_fg = '#b9b9b9'
sidebar_fg = '#b9b9b9'
footer_fg = '#b9b9b9'
modal_fg = '#b9b9b9'

# ========= Special Color =========
cursor = '#b9b9b9'
correct = '#6E6A64'
error = '#8f6969'
hint = '#868686'
cancel = '#8f6969'
gradient_color = ['#0d0d0c', "#525252"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#0d0d0c'
file_panel_top_path = '#525252'
file_panel_item_selected_fg = '#525252'
file_panel_item_selected_bg = '#0d0d0c'

# ========= Sidebar Special Items =========
sidebar_title = '#ffffff'
sidebar_item_selected_fg = '#525252'
sidebar_item_selected_bg = '#0d0d0c'
sidebar_divider = '#b9b9b9'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#8f6969'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#6E6A64'
